keys:
  - &edger_2022-09-01 age1rzrhkd478y0txalg85lpey7pmn0x3cm5ufalxslsvfrw92dl3e8qcmywvc
  - &edger_host age1w37yymreuhwygpfcnntrxyrrrk9jvht5057enleu2r4fnzxhzy5s6jyt2p
  - &a13_host age1acawzy46wfd98qrx93yrafyeqn3etg6s7k4z5t59mm7vjh5eyf9ssr7sh9
  - &g1_host age1kndmmujxnm43k85grj9qajpyx4k7l47crf7fd66ez56nn4u5rp5qdmwu8e
  - &pc_host age1yvux7svkagtk2cpjzedv87qec3a602hlk3a38weemfcj2vsyt4sssa2xwt
  - &p2_host age1vsyyrt3w8t67ful3t7722jslt99dz0tdh8v8p0ayrw37mxmdkgaqgfm5sh
creation_rules:
  - path_regex: \/secrets\/.+\.(yaml|json|md|txt|fish)$
    key_groups:
      - age:
        - *edger_2022-09-01
        - *edger_host
        - *a13_host
        - *g1_host
        - *pc_host
        - *p2_host
  - path_regex: \/secret\..+\.(yaml|json|md|txt|fish)$
    key_groups:
      - age:
        - *edger_2022-09-01
        - *edger_host
        - *a13_host
        - *g1_host
        - *pc_host
        - *p2_host

