-- Generated by Home Manager.
-- See https://wezfurlong.org/wezterm/

local wezterm = require 'wezterm'

local wezterm = require 'wezterm'
local act = wezterm.action

wezterm.on('format-tab-title', function(tab)
    local title = tab.active_pane.title
    return title:match('^(.-)%s*|') or title
end)

return {
    set_environment_variables = {
        COLORTERM = 'truecolor',
    },
    audible_bell = 'Disabled',
    enable_wayland = true,
    -- window_decorations = 'INTEGRATED_BUTTONS|RESIZE',
    window_decorations = 'NONE',

    --font_dirs = { '/run/current-system/sw/share/X11/fonts' },
    --font = wezterm.font 'FiraCode Nerd Font Mono',
    font = wezterm.font 'Hurmit Nerd Font Mono',

    color_scheme = 'Tokyo Night',

    hide_tab_bar_if_only_one_tab = true,

    enable_kitty_keyboard = true,

    keys = {
        { key = '1',          mods = 'CTRL',       action = act.ActivateTab(0), },
        { key = '2',          mods = 'CTRL',       action = act.ActivateTab(1), },
        { key = '3',          mods = 'CTRL',       action = act.ActivateTab(2), },
        { key = '4',          mods = 'CTRL',       action = act.ActivateTab(3), },
        { key = '5',          mods = 'CTRL',       action = act.ActivateTab(4), },
        { key = '6',          mods = 'CTRL',       action = act.ActivateTab(5), },
        { key = '7',          mods = 'CTRL',       action = act.ActivateTab(6), },
        { key = '8',          mods = 'CTRL',       action = act.ActivateTab(7), },
        { key = '9',          mods = 'CTRL',       action = act.ActivateTab(8), },
        { key = '0',          mods = 'CTRL',       action = act.ActivateTab(9), },
        { key = 'LeftArrow',  mods = 'CTRL',       action = act.ActivateTabRelative(-1) },
        { key = 'RightArrow', mods = 'CTRL',       action = act.ActivateTabRelative(1) },
        { key = '1',          mods = 'CTRL|ALT',   action = act.MoveTab(0), },
        { key = '2',          mods = 'CTRL|ALT',   action = act.MoveTab(1), },
        { key = '3',          mods = 'CTRL|ALT',   action = act.MoveTab(2), },
        { key = '4',          mods = 'CTRL|ALT',   action = act.MoveTab(3), },
        { key = '5',          mods = 'CTRL|ALT',   action = act.MoveTab(4), },
        { key = '6',          mods = 'CTRL|ALT',   action = act.MoveTab(5), },
        { key = '7',          mods = 'CTRL|ALT',   action = act.MoveTab(6), },
        { key = '8',          mods = 'CTRL|ALT',   action = act.MoveTab(7), },
        { key = '9',          mods = 'CTRL|ALT',   action = act.MoveTab(8), },
        { key = '0',          mods = 'CTRL|ALT',   action = act.MoveTab(9), },
        { key = 'LeftArrow',  mods = 'CTRL|ALT',   action = act.MoveTabRelative(-1) },
        { key = 'RightArrow', mods = 'CTRL|ALT',   action = act.MoveTabRelative(1) },
        -- on linux, this cause ` key not working for some reason
        -- { key = '`', modes = "CTRL", action = act.SendString('\x1b[96;5u')},
        { key = 'c', mods = 'CTRL|SHIFT', action = wezterm.action_callback(function(window, pane)
            local sel = window:get_selection_text_for_pane(pane)
            if sel and sel ~= '' then
                window:perform_action(act.CopyTo('Clipboard'), pane)
            end
        end)},
        { key = 'v', mods = 'CTRL|SHIFT', action = act.PasteFrom('Clipboard') },
        { key = '\\', mods = 'CTRL', action = wezterm.action_callback(function(window, pane)
            -- This is for multiple line editing in Claude Code, the delay is needed here
            -- otherwise an extra \ will be left in last line
            window:perform_action(act.SendKey { key = 'Space' }, pane)
            window:perform_action(act.SendKey { key = 'Backslash' }, pane)
            wezterm.sleep_ms(50) -- Delay 50ms
            window:perform_action(act.SendKey { key = 'Enter' }, pane)
        end)},
    },
}

