sync-from-skills:
  mkdir -p skills/
  cp -vr ~/.skills/ctx-clarify skills/
  cp -vr ~/.skills/ctx-organize skills/

  mkdir -p hooks/
  cp -vr ~/.skills/.claude/hooks/save-plan.sh hooks/

  mkdir -p ctx/
  cp -vr ~/.skills/ctx-beans ctx/beans
