version = 1

[install]
lazyjj.pkg-path = "lazyjj"
simple-http-server.pkg-path = "simple-http-server"
libinput.pkg-path = "libinput"
libinput.systems = ["x86_64-linux", "aarch64-linux"]
xdotool.pkg-path = "xdotool"
xdotool.systems = ["x86_64-linux", "aarch64-linux"]
libgbm.pkg-path = "libgbm"
libgbm.systems = ["x86_64-linux", "aarch64-linux"]
