default:
  @just install
  @just nix-config

nix-config:
  mkdir -p ~/.config/nix
  cp nix.conf ~/.config/nix

install:
  @just linux_apt_install-dependencies

  # https://nixos.org/download/#nix-install-linux
  sh <(curl --proto '=https' --tlsv1.2 -L https://nixos.org/nix/install) --daemon

linux_apt_install-dependencies:
  sudo apt update
  sudo apt install curl just
